# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2e9c394ce2038b67d2ddf600332386acec680409c403724eb748cc6b2746f20c6f23bceeeebcb79cbcb63ece4489daae2d694d598df120c48f50618af1d7c3

test:
  secret_key_base: 540827ed8053eeebb2fb81348c483db35624e496502571ed133b3a43d5846f0b8e24446616eb6d91d04aa7ab371c18a4ea0cde229b164975c20975f2d768f4aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
